### PR TITLE
Fixed precision of g:Date values to milliseconds

### LINKED ISSUE #128: Date Type At Wrong Precision?
I believe the Date is at the wrong precision?

At this location:
https://github.com/wolf4ood/gremlin-rs/blob/c6936ad5981e7ce8b32ae31261e942644cd42abc/gremlin-client/src/io/mod.rs#L65

It calls `d.timestamp()` which `Returns the number of non-leap **seconds** since January 1, 1970 0:00:00 UTC`

However at least according to the [Tinkerpop docs](http://tinkerpop.apache.org/docs/current/dev/io/#_date_2/) it has for Date: 
`Representing a **millisecond**-precision offset from the unix epoch. In Java, it is simply Date.getTime().` 

I believe that method should instead be `d.timestamp_millis()`

Doing that corrected writing the timestamp so it's correct when viewed in a gremlin session.

To fix parsing it in the library I believe this needs to be changed
https://github.com/wolf4ood/gremlin-rs/blob/2e18b3cb09217a1c7f9645f98ce98a90a69acfab/gremlin-client/src/io/serializer_v3.rs#L45

to `Ok(GValue::from(Utc.timestamp_millis(val)))`

But this will naturally have significant impact on anyone who's using this library currently for any values that were serialized as epoch seconds in conflict with the Tinkerpop spec.

### PR DESCRIPTION
**Pull request by criminosis**
Closes #128 

This PR is a breaking change upon dates that are currently serialized since they would be serialized as epoch seconds not epoch milliseconds, but the Tinkerpop standard for [version 2](http://tinkerpop.apache.org/docs/current/dev/io/#_date) and [version 3](http://tinkerpop.apache.org/docs/current/dev/io/#_date_2) expects milliseconds.

Given the library is still major version 0 such breaking changes are permitted per semver expectations, but wanted to call it out for your consideration when reviewing.

### CODE REVIEW

File: gremlin-client/src/io/mod.rs [hunk 1]
```diff
@@ -59,10 +59,10 @@ impl GraphSON {
                 "@type" : "g:UUID",
                 "@value" : s.to_string()
             })),
-            (GraphSON::V1, GValue::Date(d)) => Ok(json!(d.timestamp())),
+            (GraphSON::V1, GValue::Date(d)) => Ok(json!(d.timestamp_millis())),
```
Comment (criminosis) [inline gremlin-client/src/io/mod.rs:62]: Touching the GraphSON V1 implementation is something I flip-flopped on since as far as I can tell in the [docs] (http://tinkerpop.apache.org/docs/current/dev/io/#graphson-1d0) there is no spec definition for a date, it's just some integer value, which seems consistent with the test I ended up modifying in gremlin-client/tests/integration_client_v1.rs.

In that test the value is parsed out as a `i64` so I think there's an argument to be made that there is no millisecond precision expectation in the v1 standard so it could be left as is as epoch second but for now I went for consistency with v2 and v3. Let me know if you feel like I should have left it alone @wolf4ood

**Comment by wolf4ood** [comment]
Thanks :+1:  :)
